### ISSUE TITLE
Service account "controller" missing?

### ISSUE THREAD

**Issue by SelfhostedPro** [knative-sandbox/net-certmanager#388]
Hey, I'm working on getting net-certmanager setup with kourier and knative-serving but I'm running into the following error:
```
pods "net-certmanager-controller-6f7bc9488c-" is forbidden: error
        looking up service account tools/controller: serviceaccount "controller"
        not found
```

Am I able to use a non-default namespace for this? Currently I'm deploying things into the tools namespace but can change if that's not compatible with this project. This is my kustomization.yaml:

```yaml
bases:
  - "https://github.com/knative/operator/releases/download/knative-v1.3.1/operator.yaml"
  - "https://github.com/knative/net-kourier/releases/download/knative-v1.3.0/kourier.yaml"
  - "https://github.com/knative/net-certmanager/releases/download/knative-v1.3.0/release.yaml"
patchesStrategicMerge:
  - overlays/knative-operator-sa.yaml # This just adds a role binding via IRSA for read access to ecr

namespace: tools
```
